apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podname-http
  namespace: demo
  labels:
    app: podname-http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podname-http
  template:
    metadata:
      labels:
        app: podname-http
    spec:
      containers:
        - name: podname-http
          image: ghcr.io/olegdunkan/test-srv:5.0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: podname-http
  namespace: demo
spec:
  type: NodePort
  selector:
    app: podname-http
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30090